FROM node:21

WORKDIR /app
RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml ./
COPY backend ./backend

RUN yarn workspaces focus backend --production

EXPOSE 3001

CMD ["yarn", "workspace", "backend", "start"]
