const filterOptions = ['top', 'jungle', 'mid', 'ad', 'sup'];

const lineMapping: Record<string, number> = {
  top: 0,
  jungle: 1,
  mid: 2,
  ad: 3,
  sup: 4,
};

const roleOptions = {
  HOST: 'host',
  GUEST: 'guest',
  AUD: 'audience',
} as const;

const teamSideOptions = {
  BLUE: 'blue',
  RED: 'red',
  AUD: 'audience',
} as const;

const sideOptions = {
  LEFT: 'left',
  RIGHT: 'right',
} as const;

const InitailizeInfoData = {
  blurb: '',
  id: '',
  key: '',
  name: '',
  partype: '',
  tags: [],
  title: '',
  version: '',
  status: '',
  line: [],
};

const InitializeBanPickObject = [
  {
    index: 0,
    location: 'blueBan1',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 1,
    location: 'redBan1',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 2,
    location: 'blueBan2',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 3,
    location: 'redBan2',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 4,
    location: 'blueBan3',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 5,
    location: 'redBan3',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 6,
    location: 'bluePick1',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 7,
    location: 'redPick1',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 8,
    location: 'redPick2',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 9,
    location: 'bluePick2',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 10,
    location: 'bluePick3',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 11,
    location: 'redPick3',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 12,
    location: 'redBan4',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 13,
    location: 'blueBan4',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 14,
    location: 'redBan5',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 15,
    location: 'blueBan5',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'ban',
  },
  {
    index: 16,
    location: 'redPick4',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 17,
    location: 'bluePick4',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 18,
    location: 'bluePick5',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
  {
    index: 19,
    location: 'redPick5',
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: 'pick',
  },
];

export {
  filterOptions,
  roleOptions,
  teamSideOptions,
  lineMapping,
  sideOptions,
  InitailizeInfoData,
  InitializeBanPickObject,
};
