import { lineOptions, locationOptions, statusOptions, teamcolorOptions } from '.';

const InitailizeInfoData = {
  blurb: '',
  id: '',
  key: '',
  name: '',
  partype: '',
  tags: [],
  title: '',
  version: '',
  status: '',
  line: [],
};

const InitializeBanPickObject = [
  {
    index: 0,
    location: locationOptions.BLUEB1,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 1,
    location: locationOptions.REDB1,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 2,
    location: locationOptions.BLUEB2,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 3,
    location: locationOptions.REDB2,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 4,
    location: locationOptions.BLUEB3,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 5,
    location: locationOptions.REDB3,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 6,
    location: locationOptions.BLUEP1,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 7,
    location: locationOptions.REDP1,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 8,
    location: locationOptions.REDP2,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 9,
    location: locationOptions.BLUEP2,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 10,
    location: locationOptions.BLUEP3,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 11,
    location: locationOptions.REDP3,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 12,
    location: locationOptions.REDB4,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 13,
    location: locationOptions.BLUEB4,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 14,
    location: locationOptions.REDB5,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 15,
    location: locationOptions.BLUEB5,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.BAN,
  },
  {
    index: 16,
    location: locationOptions.REDP4,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 17,
    location: locationOptions.BLUEP4,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 18,
    location: locationOptions.BLUEP5,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
  {
    index: 19,
    location: locationOptions.REDP5,
    name: '',
    info: InitailizeInfoData,
    use: false,
    random: false,
    status: statusOptions.PICK,
  },
];

const InitializeSelectedTeam = [
  { color: teamcolorOptions.BLUE, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.RED, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.RED, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.RED, banpick: statusOptions.BAN, line: lineOptions.NO },
  // 1번 밴 끝
  { color: teamcolorOptions.BLUE, banpick: statusOptions.PICK, line: lineOptions.TOP },
  { color: teamcolorOptions.RED, banpick: statusOptions.PICK, line: lineOptions.TOP },
  { color: teamcolorOptions.RED, banpick: statusOptions.PICK, line: lineOptions.JUG },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.PICK, line: lineOptions.JUG },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.PICK, line: lineOptions.MID },
  { color: teamcolorOptions.RED, banpick: statusOptions.PICK, line: lineOptions.MID },
  // 1번 픽 끝
  { color: teamcolorOptions.RED, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.RED, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.BAN, line: lineOptions.NO },
  { color: teamcolorOptions.RED, banpick: statusOptions.PICK, line: lineOptions.AD },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.PICK, line: lineOptions.AD },
  { color: teamcolorOptions.BLUE, banpick: statusOptions.PICK, line: lineOptions.SUP },
  { color: teamcolorOptions.RED, banpick: statusOptions.PICK, line: lineOptions.SUP },
  // 2번 픽 끝
  { color: teamcolorOptions.NO, banpick: statusOptions.NO, line: lineOptions.NO },
];

const InitializeCurrentSelectedPick = [
  {
    name: '',
    info: InitailizeInfoData,
  },
];

export { InitailizeInfoData, InitializeBanPickObject, InitializeSelectedTeam, InitializeCurrentSelectedPick };
